import React, { Component } from "react"
import Link from "gatsby-link"
import Helmet from "react-helmet"
import { Container, Header, Divider, List, Grid, Item, Icon } from 'semantic-ui-react'

export default class Resume extends React.Component {
  componentWillMount() {
    this.setState({
      sections : [
        {
          sectionName: 'FluxNote',
          link: "https://github.com/Ali-Ni/fluxnote",
          entries : [
            'Java, Native Android',
            "3rd place winner at Electric City Hacks 2017! FluxNote is a portable alternative to graphics tablets. The app lets users draw digitally using only their phone and a magnetic pen. The phone's magnetometer is used to detect magnetic field strength, and this data is then used to locate the position of the pen relative to the phone."
          ],
          links : [
            {name: 'android', text: "Available on Google Play!", link : "https://play.google.com/store/apps/details?id=com.derekxu.pianochordpads", color: 'green'}
          ],
        },
        {
          sectionName: 'Finden',
          link: "https://github.com/shunr/finden",
          entries : [
            'Java, Native Android',
            "Made at Hack the North 2017! Finden is a massively multiplayer scavenger hunt game. Users get points for taking pictures of target objects from a list generated by the game. Features a real-time global leaderboard created with Firebase and uses the Watson API."
          ],
          links : [
            {name: 'android', text: "Available on Google Play!", link : "https://play.google.com/store/apps/details?id=com.derekxu.pianochordpads", color: 'green'}
          ],
        },
        {
          color: "blue",
          sectionName: 'Piano Chord Pads',
          link: "https://github.com/PlumSauc3/Piano-Chord-Pads",
          entries : [
            'Java, Native Android',
            'A tool for musicians and songwriters on the go. It allows users to choose six chords that can be played by tapping on pads. My app has received over 1000 downloads on the Google Play Store'
          ],
          links : [
            {name: 'android', text: "Available on Google Play!", link : "https://play.google.com/store/apps/details?id=com.derekxu.pianochordpads", color: 'green'}
          ],
        },
        {
          sectionName: 'Circle Memory Game',
          link: "https://github.com/PlumSauc3/Circle-Memory-Game",
          entries : [
            'C++, OpenFrameworks',
            "A memory game that I wrote in C++ using OpenFrameworks. Circles are displayed on screen on the start of each round and disappear after a short amount of time. The player's objective is to find all of the hidden circles without missing more than 3 times!"
          ],
          links : [
            
          ],
        },
        {
          sectionName: 'Derek Xu Music Reivews',
          link: "https://github.com/PlumSauc3/Derek-Xu-Music-Reviews",
          entries : [
            'JavaScript, React+Redux, Semantic UI, Spotify API, Python, Flask',
            'A music review website where I personally make lists of music that I enjoyed. The frontend is written in React+Redux with Semantic UI styling. The backend uses a Python Flask app to gather album data from the Spotify API.'
          ],
          links : [
            {name: 'music', text: "Read my reviews here!", link : "https://plumsauc3.github.io/Derek-Xu-Music-Reviews/", color : 'blue'}
          ],
        },
        {
          sectionName: 'Personal Website',
          link: "https://github.com/PlumSauc3/Derek-Xu-Personal-Website",
          entries : ['Gatsby, React, Semantic UI', "The website you're looking at right now! Created with React using the GatsbyJS library. Designed with Semantic UI."],
          links : [
            
          ],
        }
      ]
    })
  }
  render() {
    return (
      <div style={{background:'linear-gradient(to bottom right, #4267b2, #92a2dd)', width:'100%', minHeight:'100%', padding:'60px 14px 20px 14px'}}>
        <Item.Group divided style={{maxWidth:700, margin:'0px auto 0px auto'}}>
          {this.state.sections.map((sect, i) => {
            return <Project title={sect.sectionName} text={sect.entries[1]} tech={sect.entries[0]} link={sect.link} key={i} links={sect.links}/>
          })}
        </Item.Group>
      </div>
    )
  }
}

class Project extends Component {
  render() {
    return (
      <Item>
        <Item.Content>
          <Item.Header as='a' href={this.props.link} style={{color:'orange'}}>
            {this.props.title}
          </Item.Header>
          <Item.Meta style={{color:'white'}}>{this.props.tech}</Item.Meta>
          <Item.Description style={{color:'#ededed', fontSize:16}}> {this.props.text} </Item.Description>
        </Item.Content>
      </Item>
    )
  }
}